apiVersion: v1
kind: Service
metadata:
  name: npu-imagegen
spec:
  type: {{ .Values.service.type }}
  selector:
    app: npu-imagegen
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
